name: .NET Shield Service CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
      - 'hotfix/**'
      - 'release/**'
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

env:
  PROJ_SERVICE_NAME: "vl-shield"
  PROJ_K8S_NAMESPACE_BASE: "shield"
  PROJ_HARBOR_DIRECTORY: "dpvl"
  PROJ_SOLUTION_NAME: "DPVL.Shield"
  PROJ_IMAGE_NAME: "dpvl.shield"
  TMPL_DOCKER_FILE_PATH: "./DPVL.Shield.WebService/Dockerfile"
  TMPL_UNIT_TEST_IMAGE: "mcr.microsoft.com/dotnet/sdk:9.0"

jobs:
  dotnet-service-pipeline:
    uses: rdoddicei/gitlab-github/.github/workflows/dotnet-service-pipeline.yml@main
    with:
      PROJ_SERVICE_NAME: "vl-shield"
      PROJ_K8S_NAMESPACE_BASE: "shield"
      PROJ_HARBOR_DIRECTORY: "dpvl"
      PROJ_SOLUTION_NAME: "DPVL.Shield"
      PROJ_IMAGE_NAME: "dpvl.shield"
      TMPL_DOCKER_FILE_PATH: "./DPVL.Shield.WebService/Dockerfile"
      TMPL_UNIT_TEST_IMAGE: "mcr.microsoft.com/dotnet/sdk:9.0"
      TMPL_SONAR_IMAGE: "harbor.use.ucdp.net/utp_common/upr-dotnet-sonarqube-image:dotnet-sdk-7.0"
      CI_COMMIT_BRANCH: ${{ github.ref_name }}
      CI_DEFAULT_BRANCH: "main"
      CI_MERGE_REQUEST_ID: ${{ github.event.number }}
    secrets: inherit
